### ISSUE TITLE
Dropdown theme!

### ISSUE THREAD

**Issue by andresbermeoq** [olacin/telescope-cc.nvim#10]
Hello @olacin , I had been implementing the plugin, but the first page works well, however, in the commands (scope, commit_message) are called within cmd!... Maybe he was implementing my configuration wrong.
[Screencast from 2024-05-21 15-59-48.webm](https://github.com/olacin/telescope-cc.nvim/assets/24640851/11fd8a14-b62e-466a-826e-f42ee084d988)

**Comment by olacin** [comment]
Hey @andresbermeoq, this is actually the classic behavior of Neovim when you use `vim.cmd`.
If you'd like to get a similar UI as the demo one, I would recommend you take a look adding a plugin like [dressing.nvim](https://github.com/stevearc/dressing.nvim), which is the one I used in the demo !

**Comment by andresbermeoq** [comment]
Thanks @olacin, I configured the plugin and works well. Thanks for your help.
