### ISSUE TITLE
Fails when used with `dressing.nvim`

### ISSUE THREAD

**Issue by hinell** [olacin/telescope-cc.nvim#5]
[dressing.nvim](https://github.com/stevearc/dressing.nvim) replaces native `vim.ui.input`.

When plugin is called, two input windows are overlaid or even replaced and nothing happens after entering.

It seems like it's impossible to have two dressing input windows at the time.

**Comment by olacin** [comment]
Hi, thanks for the issue !

I don't have much bandwidth at the moment, but I am open for a PR if you're up to.

In the meantime, I would recommend you to find an alternative to dressing.nvim or to use the native `vim.ui.input`. 🙁

**Comment by hinell** [comment]
Dressing **input** UI may be disabled via config as workaround (doesn't affect anything else):
```lua
require("dressing").setup({
	input  = {
		 enabled = false
	}
	-- ...
})
```

**Comment by olacin** [comment]
Hey @hinell, I'm happy to share that dressing.nvim integration has been fixed and was caused by the asynchronous behavior of `vim.ui.input` !

Have a good one 👋
